name: Clean Deploy via Temp Folder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST2 }}
          username: ${{ secrets.USERNAME2 }}
          key: ${{ secrets.SSH_PASS }}
          port: 22
          debug: true
          script_stop: true
          command_timeout: 2m
          script: |
            echo "TEST_MARKER_START"
            whoami
            pwd
            date
            ls -la /home/c/cs16144/www452 2>&1 || echo "PATH_NOT_FOUND"
            echo "TEST_MARKER_END"