name: Deploy with Rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to server via Rsync
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Переходимо в папку, де лежить ваш .git
            cd /var/www/www-root/data/www/sanchos-dev.website

            # Оновлюємо код у прихованій частині (git repo)
            git fetch origin main
            git reset --hard origin/main

            # ВИДАЛЯЄМО .DS_Store на сервері, якщо вони там вже були
            find . -name ".DS_Store" -delete

            # Синхронізуємо файли в робочу директорію сайту
            # Прапорець --delete видаляє на сервері ті файли, яких вже немає в гіті
            # --exclude гарантує, що службові файли не потраплять у публічний доступ
            rsync -avz --delete \
              --exclude='.git/' \
              --exclude='.github/' \
              --exclude='.gitignore' \
              --exclude='.gitattributes' \
              --exclude='.DS_Store' \
              ./ ./

            echo "Сайт очищено та оновлено."